version: '3.3'
services:

  frontend:
    image: vtolstopyatov/foodgram-frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ../.env
  web:
    image: vtolstopyatov/foodgram:v1
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn foodgram.wsgi:application --bind 0:8000"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ../.env
  nginx:
    image: nginx:1.25.2
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  postgres_value:
