# Generated by Django 4.1.3 on 2023-04-09 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientsamount',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipes'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ingredientsamount',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientsamount',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredients'),
        ),
    ]
