# Generated by Django 4.1.3 on 2023-04-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipes_ingredients_ingredientsamount_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsamount',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientsamount',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
            preserve_default=False,
        ),
    ]
