# Generated by Django 4.1.3 on 2023-07-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoppingcart_delete_shoppingbag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
